// Regenerates packages/one_ui/lib/src/tokens/one_tokens.g.dart from the
// "Devstrike One: Aso-oke" design tokens that live in the TypeScript monorepo
// (devstrike-one/packages/design-tokens/tokens.json).
//
// Usage (from the workspace root):
//
//   dart run tool/sync_tokens.dart                 # sibling checkout
//   dart run tool/sync_tokens.dart --source <path> # explicit tokens.json
//   ONE_TOKENS_PATH=<path> dart run tool/sync_tokens.dart
//   dart run tool/sync_tokens.dart --check         # CI: fail if stale
//
// The script also copies the source JSON to packages/one_ui/tokens/tokens.json
// so the Flutter workspace builds without the TypeScript repo checked out, and
// so a token change shows up as a reviewable diff here.
//
// It deliberately reads the JSON rather than the Dart file the TS package may
// emit: the JSON is the contract, and the Flutter-side shape (ThemeExtension
// friendly, `Color` constants) is ours to decide.

import 'dart:convert';
import 'dart:io';

const _defaultSource = '../devstrike-one/packages/design-tokens/tokens.json';
const _snapshotPath = 'packages/one_ui/tokens/tokens.json';
const _outputPath = 'packages/one_ui/lib/src/tokens/one_tokens.g.dart';

Future<void> main(List<String> args) async {
  final check = args.contains('--check');
  final sourceIndex = args.indexOf('--source');
  final explicit = sourceIndex >= 0 && sourceIndex + 1 < args.length
      ? args[sourceIndex + 1]
      : Platform.environment['ONE_TOKENS_PATH'];

  // Prefer the live TS repo; fall back to the committed snapshot.
  final candidates = [?explicit, _defaultSource, _snapshotPath];
  final source = candidates
      .map(File.new)
      .firstWhere(
        (f) => f.existsSync(),
        orElse: () {
          stderr.writeln(
            'No tokens.json found. Tried: ${candidates.join(', ')}',
          );
          exit(66);
        },
      );

  final raw = source.readAsStringSync();
  final json = jsonDecode(raw) as Map<String, Object?>;
  final dart = _format(generate(json));

  final output = File(_outputPath);
  final snapshot = File(_snapshotPath);
  if (check) {
    final stale =
        !output.existsSync() ||
        output.readAsStringSync() != dart ||
        !snapshot.existsSync() ||
        snapshot.readAsStringSync() != raw;
    if (stale) {
      stderr.writeln(
        'one_ui tokens are out of date with ${source.path}. '
        'Run `dart run tool/sync_tokens.dart` and commit the result.',
      );
      exit(1);
    }
    stdout.writeln('one_ui tokens are up to date (${source.path}).');
    return;
  }

  output
    ..createSync(recursive: true)
    ..writeAsStringSync(dart);
  if (source.absolute.path != snapshot.absolute.path) {
    snapshot
      ..createSync(recursive: true)
      ..writeAsStringSync(raw);
  }
  stdout.writeln('Wrote $_outputPath from ${source.path}.');
}

String _format(String code) {
  final tmp = Directory.systemTemp.createTempSync('one_tokens');
  try {
    final file = File('${tmp.path}/one_tokens.g.dart')..writeAsStringSync(code);
    final result = Process.runSync(Platform.resolvedExecutable, [
      'format',
      '--language-version=3.13',
      file.path,
    ]);
    if (result.exitCode != 0) {
      stderr.writeln(result.stderr);
      return code;
    }
    return file.readAsStringSync();
  } finally {
    tmp.deleteSync(recursive: true);
  }
}

/// Builds the Dart source for [tokens]. Kept free of I/O so it is testable.
String generate(Map<String, Object?> tokens) {
  final name = tokens['name'] as String? ?? 'Devstrike One';
  final version = tokens['version'] as String? ?? '0.0.0';
  final color = _map(tokens, 'color');
  final light = _map(color, 'light');
  final dark = _map(color, 'dark');
  final keys = light.keys.toList();
  final missing = keys.where((k) => !dark.containsKey(k)).toList();
  if (missing.isNotEmpty) {
    throw FormatException('color.dark is missing: ${missing.join(', ')}');
  }

  final b = StringBuffer()
    ..writeln('// GENERATED by tool/sync_tokens.dart. Do not edit by hand.')
    ..writeln('// Source: devstrike-one/packages/design-tokens/tokens.json')
    ..writeln('// Snapshot: packages/one_ui/tokens/tokens.json')
    ..writeln('// Tokens: $name $version')
    ..writeln()
    ..writeln('// ignore_for_file: public_member_api_docs')
    ..writeln()
    ..writeln("import 'package:flutter/animation.dart';")
    ..writeln("import 'package:flutter/painting.dart';")
    ..writeln()
    ..writeln('/// Name and version of the token set this file was built from.')
    ..writeln('abstract final class OneTokenSet {')
    ..writeln("  static const String name = '${_escape(name)}';")
    ..writeln("  static const String version = '$version';")
    ..writeln('}')
    ..writeln()
    ..writeln('/// One colour scheme (light or dark) from `color.<mode>`.')
    ..writeln('final class OneColorTokens {')
    ..writeln('  const OneColorTokens({');
  for (final k in keys) {
    b.writeln('    required this.${_camel(k)},');
  }
  b.writeln('  });');
  for (final k in keys) {
    b
      ..writeln()
      ..writeln('  /// `$k`')
      ..writeln('  final Color ${_camel(k)};');
  }
  b
    ..writeln('}')
    ..writeln();

  for (final (mode, values) in [('light', light), ('dark', dark)]) {
    b
      ..writeln('/// `color.$mode`.')
      ..writeln(
        'const OneColorTokens oneColors${_pascal(mode)} = OneColorTokens(',
      );
    for (final k in keys) {
      b.writeln('  ${_camel(k)}: ${_color(values[k])},');
    }
    b
      ..writeln(');')
      ..writeln();
  }

  final weave = _map(tokens, 'weave');
  b
    ..writeln('/// Band colours of the woven strip motif, in order (`weave`).')
    ..writeln('abstract final class OneWeaveTokens {');
  for (final mode in ['light', 'dark']) {
    final list = (weave[mode]! as List<Object?>).map(_color).join(', ');
    b.writeln('  static const List<Color> $mode = [$list];');
  }
  b
    ..writeln('}')
    ..writeln();

  final font = _map(tokens, 'font');
  b
    ..writeln('/// Font families and the weights we load (`font`).')
    ..writeln('abstract final class OneFontTokens {');
  for (final entry in font.entries) {
    final spec = entry.value! as Map<String, Object?>;
    final id = _camel(entry.key);
    final weights = (spec['weights']! as List<Object?>).join(', ');
    b
      ..writeln(
        "  static const String $id = '${_escape(spec['family']! as String)}';",
      )
      ..writeln('  static const List<int> ${id}Weights = [$weights];');
  }
  b
    ..writeln('}')
    ..writeln()
    ..write(
      _numbers(
        'OneFontSizeTokens',
        'Type scale in logical pixels (`fontSize`).',
        _map(tokens, 'fontSize'),
      ),
    )
    ..write(
      _numbers(
        'OneLineHeightTokens',
        'Line-height multipliers (`lineHeight`).',
        _map(tokens, 'lineHeight'),
      ),
    )
    ..write(
      _numbers(
        'OneRadiusTokens',
        'Corner radii in logical pixels (`radius`).',
        _map(tokens, 'radius'),
      ),
    )
    ..write(
      _numbers(
        'OneSpaceTokens',
        'Spacing scale in logical pixels (`space`).',
        _map(tokens, 'space'),
        prefix: 's',
      ),
    );

  final motion = _map(tokens, 'motion');
  final duration = _map(motion, 'duration');
  final easing = _map(motion, 'easing');
  b
    ..writeln('/// Durations and easing curves (`motion`).')
    ..writeln('abstract final class OneMotionTokens {');
  for (final e in duration.entries) {
    b.writeln(
      '  static const Duration ${_camel(e.key)} = Duration(milliseconds: ${e.value});',
    );
  }
  for (final e in easing.entries) {
    final p = (e.value! as List<Object?>).join(', ');
    b.writeln('  static const Cubic ease${_pascal(e.key)} = Cubic($p);');
  }
  b.writeln('}');
  return b.toString();
}

String _numbers(
  String cls,
  String doc,
  Map<String, Object?> values, {
  String prefix = '',
}) {
  final b = StringBuffer()
    ..writeln('/// $doc')
    ..writeln('abstract final class $cls {');
  for (final e in values.entries) {
    final v = e.value! as num;
    b.writeln(
      '  static const double ${_identifier(e.key, prefix)} = ${v.toDouble()};',
    );
  }
  return (b
        ..writeln('}')
        ..writeln())
      .toString();
}

Map<String, Object?> _map(Map<String, Object?> parent, String key) {
  final value = parent[key];
  if (value is! Map<String, Object?>) {
    throw FormatException('tokens.json: "$key" must be an object');
  }
  return Map.fromEntries(value.entries.where((e) => !e.key.startsWith(r'$')));
}

String _color(Object? hex) {
  final s = (hex! as String).replaceFirst('#', '').toUpperCase();
  if (!RegExp(r'^[0-9A-F]{6}([0-9A-F]{2})?$').hasMatch(s)) {
    throw FormatException('Not a colour: $hex');
  }
  // tokens are #RRGGBB or #RRGGBBAA; Color wants 0xAARRGGBB.
  final argb = s.length == 6 ? 'FF$s' : '${s.substring(6)}${s.substring(0, 6)}';
  return 'Color(0x$argb)';
}

String _identifier(String key, String prefix) {
  // "2xl" -> "xl2", "0" -> "s0" (with prefix), "inOut" stays.
  final numeric = RegExp(r'^(\d+)([a-z]+)$').firstMatch(key);
  if (numeric != null) return '${numeric[2]}${numeric[1]}';
  if (RegExp(r'^\d').hasMatch(key)) {
    return '${prefix.isEmpty ? 'v' : prefix}$key';
  }
  return _camel(key);
}

String _camel(String key) {
  final parts = key.split(RegExp('[-_ ]'));
  return parts.first + parts.skip(1).map(_pascal).join();
}

String _pascal(String s) => s.isEmpty ? s : s[0].toUpperCase() + s.substring(1);

String _escape(String s) => s.replaceAll(r'\', r'\\').replaceAll("'", r"\'");
