// GENERATED by tool/sync_tokens.dart. Do not edit by hand.
// Source: devstrike-one/packages/design-tokens/tokens.json
// Snapshot: packages/one_ui/tokens/tokens.json
// Tokens: Devstrike One: Aso-oke 1.0.0

// ignore_for_file: public_member_api_docs

import 'package:flutter/animation.dart';
import 'package:flutter/painting.dart';

/// Name and version of the token set this file was built from.
abstract final class OneTokenSet {
  static const String name = 'Devstrike One: Aso-oke';
  static const String version = '1.0.0';
}

/// One colour scheme (light or dark) from `color.<mode>`.
final class OneColorTokens {
  const OneColorTokens({
    required this.paper,
    required this.surface,
    required this.surface2,
    required this.surface3,
    required this.ink,
    required this.inkMuted,
    required this.inkFaint,
    required this.line,
    required this.lineStrong,
    required this.kola,
    required this.kolaHover,
    required this.kolaInk,
    required this.kolaWash,
    required this.river,
    required this.riverHover,
    required this.riverInk,
    required this.riverWash,
    required this.brass,
    required this.brassInk,
    required this.brassWash,
    required this.indigo,
    required this.indigoWash,
    required this.warning,
    required this.warningWash,
    required this.danger,
    required this.dangerInk,
    required this.dangerWash,
    required this.focus,
  });

  /// `paper`
  final Color paper;

  /// `surface`
  final Color surface;

  /// `surface-2`
  final Color surface2;

  /// `surface-3`
  final Color surface3;

  /// `ink`
  final Color ink;

  /// `ink-muted`
  final Color inkMuted;

  /// `ink-faint`
  final Color inkFaint;

  /// `line`
  final Color line;

  /// `line-strong`
  final Color lineStrong;

  /// `kola`
  final Color kola;

  /// `kola-hover`
  final Color kolaHover;

  /// `kola-ink`
  final Color kolaInk;

  /// `kola-wash`
  final Color kolaWash;

  /// `river`
  final Color river;

  /// `river-hover`
  final Color riverHover;

  /// `river-ink`
  final Color riverInk;

  /// `river-wash`
  final Color riverWash;

  /// `brass`
  final Color brass;

  /// `brass-ink`
  final Color brassInk;

  /// `brass-wash`
  final Color brassWash;

  /// `indigo`
  final Color indigo;

  /// `indigo-wash`
  final Color indigoWash;

  /// `warning`
  final Color warning;

  /// `warning-wash`
  final Color warningWash;

  /// `danger`
  final Color danger;

  /// `danger-ink`
  final Color dangerInk;

  /// `danger-wash`
  final Color dangerWash;

  /// `focus`
  final Color focus;
}

/// `color.light`.
const OneColorTokens oneColorsLight = OneColorTokens(
  paper: Color(0xFFF3EEE3),
  surface: Color(0xFFFBF8F1),
  surface2: Color(0xFFECE5D7),
  surface3: Color(0xFFE2D9C7),
  ink: Color(0xFF141722),
  inkMuted: Color(0xFF565866),
  inkFaint: Color(0xFF6A6A70),
  line: Color(0xFFDCD2C0),
  lineStrong: Color(0xFF8A7E69),
  kola: Color(0xFF8F3A1F),
  kolaHover: Color(0xFF772F18),
  kolaInk: Color(0xFFFFF5EC),
  kolaWash: Color(0xFFF3E0D3),
  river: Color(0xFF1D5C55),
  riverHover: Color(0xFF154A44),
  riverInk: Color(0xFFF0FAF7),
  riverWash: Color(0xFFDCEBE5),
  brass: Color(0xFFA07D2E),
  brassInk: Color(0xFF6F5213),
  brassWash: Color(0xFFF1E6C8),
  indigo: Color(0xFF2A3766),
  indigoWash: Color(0xFFE0E3EF),
  warning: Color(0xFF8A5A0E),
  warningWash: Color(0xFFF4E6CB),
  danger: Color(0xFFA22B2B),
  dangerInk: Color(0xFFFFF4F2),
  dangerWash: Color(0xFFF5DEDA),
  focus: Color(0xFF8F3A1F),
);

/// `color.dark`.
const OneColorTokens oneColorsDark = OneColorTokens(
  paper: Color(0xFF0E1017),
  surface: Color(0xFF161922),
  surface2: Color(0xFF1F2330),
  surface3: Color(0xFF2A2F3E),
  ink: Color(0xFFEFE9DD),
  inkMuted: Color(0xFFABA79D),
  inkFaint: Color(0xFF8C897F),
  line: Color(0xFF2B303F),
  lineStrong: Color(0xFF6A7287),
  kola: Color(0xFFE2835F),
  kolaHover: Color(0xFFEC9878),
  kolaInk: Color(0xFF1C0C05),
  kolaWash: Color(0xFF34201A),
  river: Color(0xFF62B7A7),
  riverHover: Color(0xFF7CC8B9),
  riverInk: Color(0xFF04201B),
  riverWash: Color(0xFF16302C),
  brass: Color(0xFFD8AE58),
  brassInk: Color(0xFFE2BE72),
  brassWash: Color(0xFF2E2716),
  indigo: Color(0xFF94A5DA),
  indigoWash: Color(0xFF1D2438),
  warning: Color(0xFFE5A84C),
  warningWash: Color(0xFF302412),
  danger: Color(0xFFEF7B72),
  dangerInk: Color(0xFF240706),
  dangerWash: Color(0xFF3A1B19),
  focus: Color(0xFFE2835F),
);

/// Band colours of the woven strip motif, in order (`weave`).
abstract final class OneWeaveTokens {
  static const List<Color> light = [
    Color(0xFF141722),
    Color(0xFF8F3A1F),
    Color(0xFFF3EEE3),
    Color(0xFF1D5C55),
    Color(0xFFA07D2E),
    Color(0xFF2A3766),
  ];
  static const List<Color> dark = [
    Color(0xFFEFE9DD),
    Color(0xFFE2835F),
    Color(0xFF161922),
    Color(0xFF62B7A7),
    Color(0xFFD8AE58),
    Color(0xFF94A5DA),
  ];
}

/// Font families and the weights we load (`font`).
abstract final class OneFontTokens {
  static const String display = 'Newsreader';
  static const List<int> displayWeights = [400, 500, 600];
  static const String ui = 'Public Sans';
  static const List<int> uiWeights = [400, 500, 600, 700];
  static const String mono = 'Martian Mono';
  static const List<int> monoWeights = [400, 500];
}

/// Type scale in logical pixels (`fontSize`).
abstract final class OneFontSizeTokens {
  static const double xs = 12.0;
  static const double sm = 14.0;
  static const double base = 16.0;
  static const double lg = 18.0;
  static const double xl = 22.0;
  static const double xl2 = 28.0;
  static const double xl3 = 36.0;
  static const double xl4 = 48.0;
  static const double xl5 = 64.0;
}

/// Line-height multipliers (`lineHeight`).
abstract final class OneLineHeightTokens {
  static const double tight = 1.1;
  static const double snug = 1.3;
  static const double normal = 1.5;
  static const double relaxed = 1.65;
}

/// Corner radii in logical pixels (`radius`).
abstract final class OneRadiusTokens {
  static const double none = 0.0;
  static const double xs = 2.0;
  static const double sm = 4.0;
  static const double md = 6.0;
  static const double lg = 10.0;
  static const double pill = 999.0;
}

/// Spacing scale in logical pixels (`space`).
abstract final class OneSpaceTokens {
  static const double s0 = 0.0;
  static const double s1 = 4.0;
  static const double s2 = 8.0;
  static const double s3 = 12.0;
  static const double s4 = 16.0;
  static const double s5 = 20.0;
  static const double s6 = 24.0;
  static const double s8 = 32.0;
  static const double s10 = 40.0;
  static const double s12 = 48.0;
  static const double s16 = 64.0;
  static const double s20 = 80.0;
  static const double s24 = 96.0;
}

/// Durations and easing curves (`motion`).
abstract final class OneMotionTokens {
  static const Duration fast = Duration(milliseconds: 150);
  static const Duration base = Duration(milliseconds: 200);
  static const Duration slow = Duration(milliseconds: 280);
  static const Cubic easeOut = Cubic(0.2, 0.7, 0.2, 1);
  static const Cubic easeInOut = Cubic(0.65, 0, 0.35, 1);
}
