import 'package:flutter/services.dart';
import 'package:flutter_appauth/flutter_appauth.dart';
import 'package:one_auth/src/one_auth_config.dart';
import 'package:one_auth/src/token_set.dart';
import 'package:one_core/one_core.dart';

/// Talks to One ID. Implementations throw [OneFailure]s.
abstract interface class OneAuthenticator {
  /// Runs the browser sign-in and returns fresh tokens.
  Future<TokenSet> signIn({String? loginHint});

  /// Exchanges the refresh token of [current] for new tokens.
  Future<TokenSet> refresh(TokenSet current);

  /// Ends the One ID browser session (best effort).
  Future<void> endSession(TokenSet current);
}

/// [OneAuthenticator] backed by AppAuth (Android) / AppAuth-iOS.
///
/// PKCE (S256), `state` and `nonce` are generated by AppAuth. The system
/// browser is used (Custom Tabs / ASWebAuthenticationSession) so One ID
/// cookies are shared with other apps signing in through One.
class AppAuthAuthenticator implements OneAuthenticator {
  /// Creates an authenticator for [config].
  AppAuthAuthenticator(this.config, {FlutterAppAuth? appAuth})
    : _appAuth = appAuth ?? const FlutterAppAuth();

  /// Client configuration.
  final OneAuthConfig config;
  final FlutterAppAuth _appAuth;
  static final Logger _log = Logger('one_auth');

  @override
  Future<TokenSet> signIn({String? loginHint}) => _guard(() async {
    final response = await _appAuth.authorizeAndExchangeCode(
      AuthorizationTokenRequest(
        config.clientId,
        config.redirectUrl,
        issuer: config.issuer.toString(),
        scopes: config.scopes,
        loginHint: loginHint,
        allowInsecureConnections: config.allowInsecureConnections,
      ),
    );
    return _toTokenSet(response);
  });

  @override
  Future<TokenSet> refresh(TokenSet current) => _guard(() async {
    if (!current.canRefresh) throw const UnauthorizedFailure();
    final response = await _appAuth.token(
      TokenRequest(
        config.clientId,
        config.redirectUrl,
        issuer: config.issuer.toString(),
        refreshToken: current.refreshToken,
        scopes: config.scopes,
        allowInsecureConnections: config.allowInsecureConnections,
      ),
    );
    return current.refreshedWith(_toTokenSet(response));
  }, refreshing: true);

  @override
  Future<void> endSession(TokenSet current) async {
    if (current.idToken == null) return;
    try {
      await _appAuth.endSession(
        EndSessionRequest(
          idTokenHint: current.idToken,
          postLogoutRedirectUrl: config.postLogoutRedirectUrl,
          issuer: config.issuer.toString(),
          allowInsecureConnections: config.allowInsecureConnections,
        ),
      );
    } on PlatformException catch (e) {
      // The local session is cleared regardless; a failed browser logout
      // only means the One ID cookie lives until it expires.
      _log.info('endSession did not complete: ${e.code}');
    }
  }

  TokenSet _toTokenSet(TokenResponse response) {
    final access = response.accessToken;
    if (access == null || access.isEmpty) {
      throw const UnexpectedFailure(
        code: 'AUTH_NO_TOKEN',
        message: 'One ID did not return a session. Please try again.',
      );
    }
    return TokenSet(
      accessToken: access,
      refreshToken: response.refreshToken,
      idToken: response.idToken,
      // Assume a short life when the server omits expires_in.
      expiresAt:
          (response.accessTokenExpirationDateTime ??
                  OneTime.nowUtc().add(const Duration(minutes: 5)))
              .toUtc(),
      scopes: response.scopes ?? config.scopes,
    );
  }

  Future<T> _guard<T>(
    Future<T> Function() run, {
    bool refreshing = false,
  }) async {
    try {
      return await run();
    } on FlutterAppAuthUserCancelledException catch (e) {
      throw CancelledFailure(message: 'Sign-in was cancelled.', cause: e);
    } on FlutterAppAuthPlatformException catch (e) {
      final error = e.platformErrorDetails.error;
      _log.warning('AppAuth failed: ${e.code} $error');
      if (refreshing && error == 'invalid_grant') {
        throw UnauthorizedFailure(
          message: 'Your session has ended. Please sign in again.',
          cause: e,
        );
      }
      if (e.code.contains('discovery') || error == null) {
        throw NetworkFailure(
          message:
              'We could not reach One ID. Check your connection and try again.',
          cause: e,
        );
      }
      throw UnexpectedFailure(
        code: 'AUTH_FAILED',
        message: 'We could not sign you in. Please try again.',
        cause: e,
      );
    } on PlatformException catch (e) {
      _log.warning('AppAuth platform error: ${e.code}');
      throw UnexpectedFailure(
        code: 'AUTH_FAILED',
        message: 'We could not sign you in. Please try again.',
        cause: e,
      );
    }
  }
}
